<?php

/**
 * This work, "Cheetah - https://www.cheetahwsb.com", is a derivative of "Dolphin Pro V7.4.2" by BoonEx Pty Limited - https://www.boonex.com/, used under CC-BY. "Cheetah" is licensed under CC-BY by Dean J. Bassett Jr.
 * CC-BY License - http://creativecommons.org/licenses/by/3.0/
 */

$aLangContent = array(
  '_sys_module_ads' => 'Объявления',
  '_ch_ads_Activate' => 'Активировать',
  '_ch_ads_DeActivate' => 'Деактивировать',
  '_ch_ads_Ad' => 'Объявление',
  '_ch_ads_Ad_fail_delete' => 'Невозможно удалить объявление',
  '_ch_ads_Ad_photos' => 'Фото объявления',
  '_ch_ads_Ad_succ_added' => 'Объявление удачно добавлено',
  '_ch_ads_Ad_succ_deleted' => 'Объявление удачно удалено',
  '_ch_ads_Ad_succ_updated' => 'Объявление удачно обновлено',
  '_ch_ads_Add' => 'Добавить объявление',
  '_ch_ads_Add_ad' => 'Добавить объявление',
  '_ch_ads_Administration' => 'Администрирование',
  '_ch_ads_Ads' => 'Объявления',
  '_ch_ads_Ads_profile' => 'Объявления',
  '_ch_ads_Ads_Home' => 'Главная',
  '_ch_ads_Ads_adm_stats' => 'Ожидающие объявления',
  '_ch_ads_All_ads' => 'Все',
  '_ch_ads_Apply' => 'Применить',
  '_ch_ads_Back' => 'Назад',
  '_ch_ads_Browse_All_Ads' => 'Обзор всех объявлений',
  '_ch_ads_BuyDetails1' => 'Детали купленного места:',
  '_ch_ads_BuyMsg1' => 'Вы выбрали опцию "Купить сейчас" для покупки наименования. Если Вы хотите продолжить и совершить покупку сейчас по ниже представленной цене, нажмите "Продолжить". Это позволит Вам и продавцу завершить транзакцию.',
  '_ch_ads_BuyMsg2' => 'Ваша ставка "Купить сейчас" получена. Свяжитесь с продавцом для завершения транзакции.',
  '_ch_ads_Buy_Now' => 'Купить сейчас',
  '_ch_ads_Calendar' => 'Календарь',
  '_ch_ads_Caption_error' => 'укажите заголовок от 3 до 100 символов',
  '_ch_ads_Categories' => 'Категории',
  '_ch_ads_Custom_Values' => 'Пользовательские значения',
  '_ch_ads_De-Feature_it' => 'Не избранное',
  '_ch_ads_Details' => 'Детали',
  '_ch_ads_Disapproved' => 'Отклоненные',
  '_ch_ads_Existed_images' => 'Существующие изображения',
  '_ch_ads_Feature_it' => 'В избранное',
  '_ch_ads_Featured' => 'Избранные',
  '_ch_ads_Filter' => 'Фильтр',
  '_ch_ads_Filtered_ads' => 'Отфильтрованные объявления',
  '_ch_ads_Keywords' => 'Ключевые слова',
  '_ch_ads_Life_Time' => 'Без ограничений',
  '_ch_ads_Main_category_failed_add' => 'Невозможно добавить главную категорию',
  '_ch_ads_Main_category_failed_delete' => 'Невозможно удалить главную категорию',
  '_ch_ads_Main_category_successfully_added' => 'Главная категория успешно добавлена',
  '_ch_ads_Main_category_successfully_deleted' => 'Главная категория успешно удалена',
  '_ch_ads_Manage_ads' => 'Управление',
  '_ch_ads_Manage_main' => 'Главная',
  '_ch_ads_Manage_categories_form' => 'Управление категориями',
  '_ch_ads_Moderating' => 'Модерировать (новые объявления)',
  '_ch_ads_My_Ads' => 'Мои объявления',
  '_ch_ads_Popular' => 'Популярные',
  '_ch_ads_Posted_by' => 'Выложено от',
  '_ch_ads_RSS' => 'RSS',
  '_ch_ads_Sub_category_failed_add' => 'Невозможно выполнить операцию',
  '_ch_ads_Sub_category_failed_deleted' => 'Невозможно удалить под-категорию',
  '_ch_ads_Sub_category_successfully_added' => 'Подкатегория успешно добавлена',
  '_ch_ads_Sub_category_successfully_updated' => 'Подкатегория успешно обновлена',
  '_ch_ads_Sub_category_successfully_delete' => 'Подкатегория успешно удалена',
  '_ch_ads_Text_error' => 'укажите текст поста от 3 до 65535 символов',
  '_ch_ads_Top_Rated' => 'Лучшие',
  '_ch_ads_Unit' => 'Группа ',
  '_ch_ads_Users_other_listing' => 'Объявления других пользователей',
  '_ch_ads_Warn_max_file_size' => 'Файл: {0} слишком большой для загрузки.<br>',
  '_ch_ads_Warn_max_live_days' => 'Количество дней активности объявлений',
  '_ch_ads_add_main_category' => 'Добавить главную категорию',
  '_ch_ads_add_subcategory' => 'Добавить подкатегорию',
  '_ch_ads_added_spy' => '<a href="{profile_link}">{profile_nick}</a> добавил новое объявление <a href="{ads_url}">{ads_caption}</a>',
  '_ch_ads_admin_box_desc' => '<div style="text-align: center;" class="ch-def-padding ch-def-font-large">У Вас есть {0} <a href="{1}">объявлений</a>. <a href="{2}">Нажмите здесь</a>, чтобы добавить ещё.</div>',
  '_ch_ads_caption_browse_by_day' => 'Обзор объявлений по дням: ',
  '_ch_ads_caption_city' => 'Город',
  '_ch_ads_caption_country' => 'Страна',
  '_ch_ads_category_manager' => 'Менеджер категорий',
  '_ch_ads_category_warn' => 'выберите категорию и подкатегорию',
  '_ch_ads_customFieldName1' => 'Имя 1 пользовательского поля',
  '_ch_ads_customFieldName2' => 'Имя 2 пользовательского поля',
  '_ch_ads_description_error_desc' => 'Описание должно быть не длиннее {0} символов',
  '_ch_ads_err_city' => 'пожалуйста, заполните название города',
  '_ch_ads_err_country' => 'пожалуйста, укажите страну',
  '_ch_ads_expired' => 'истекшие',
  '_ch_ads_img_succ_deleted' => 'Изображение было успешно удалено',
  '_ch_ads_last_ads' => 'Последние объявления',
  '_ch_ads_last_featured' => 'Последние избранные объявления',
  '_ch_ads_msg_access_denied' => 'Доступ запрещен',
  '_ch_ads_parent_category' => 'Родительская категория',
  '_ch_ads_pending_approval' => 'Ожидающие',
  '_ch_ads_post_text' => 'Послать текст',
  '_ch_ads_privacy_comment' => 'Комментарии доступны',
  '_ch_ads_privacy_rate' => 'Голосование доступно',
  '_ch_ads_privacy_view' => 'Просмотр доступен',
  '_ch_ads_rated_spy' => '<a href="{profile_link}">{profile_nick}</a> оценил объявление <a href="{ads_url}">{ads_caption}</a>',
  '_ch_ads_commented_spy' => '<a href="{profile_link}">{profile_nick}</a> прокомментировал объявление <a href="{ads_url}">{ads_caption}</a>',
  '_ch_ads_root' => 'В корень',
  '_ch_ads_sbs_comments' => 'Новые комментарии к объявлениям',
  '_ch_ads_search_results_by_tag' => 'Результаты поиска по тегу',
  '_ch_ads_someone_wants_to_purchase' => 'Кто-то хочет купить предмет, который Вы предложили для продажи',
  '_ch_ads_title_error_desc' => 'Название должно быть не длиннее {0} символов',
  '_ch_ads_wall_added_new' => 'добавил новое',
  '_ch_ads_wall_added_new_title' => '{0} добавил новое {1}',
  '_ch_ads_wall_added_new_items' => 'добавил {0} новых объявлений',
  '_ch_ads_wall_added_new_title_items' => '{0} добавил {1} новых объявлений',
  '_ch_ads_wall_added_new_comment' => 'прокомментировал',
  '_ch_ads_wall_added_new_title_comment' => '{0} прокомментировал {1}',
  '_ch_ads_wall_object' => 'объявление',
  '_ch_ads_wholesale' => 'оптом',
  '_ch_ads_you_have_purchased_an_item' => 'Вы приобрели товар',
  '_mma_ads_add' => 'Объявления: добавлять',
  '_mma_ads_approving' => 'Объявления: одобрять',
  '_mma_ads_browse' => 'Объявления: просматривать',
  '_mma_ads_delete_any_ad' => 'Объявления: удалять любые',
  '_mma_ads_edit_any_ad' => 'Объявления: изменять любые',
  '_mma_ads_search' => 'Объявления: искать',
  '_mma_ads_view' => 'Объявления: просматривать',
  '_wall_reposted_ads_create' => 'зарепостил объявление',
  '_wall_reposted_title_ads_create' => '{0} зарепостил объявление',
  '_wall_reposted_ads_comment_add' => 'зарепостил комментарий к объявлению',
  '_wall_reposted_title_ads_comment_add' => '{0} зарепостил комментарий к объявлению',
  '_sbs_txt_title_ads' => 'Объявления',
);
