<?php

/**
 * This work, "Cheetah - https://www.cheetahwsb.com", is a derivative of "Dolphin Pro V7.4.2" by BoonEx Pty Limited - https://www.boonex.com/, used under CC-BY. "Cheetah" is licensed under CC-BY by Dean J. Bassett Jr.
 * CC-BY License - http://creativecommons.org/licenses/by/3.0/
 */

$aLangContent = array(
    '_sys_module_site_customize' => 'Дизайн Сайта',
    '_ch_sctr' => 'Дизайн Сайта',
	'_ch_sctr_mmenu_item_description' => 'Настроить дизайн сайта',
    '_ch_sctr_page_themes' => 'Темы',
    '_ch_sctr_page_background' => 'Фон',
    '_ch_sctr_page_font' => 'Шрифты',
    '_ch_sctr_page_border' => 'Границы',
    '_ch_sctr_page_themes_my' => 'Мои темы',
    '_ch_sctr_page_themes_shared' => 'Общие темы',
    '_ch_sctr_page_import' => 'Импорт',
    '_ch_sctr_theme' => 'Тема',
    '_ch_sctr_btn_save' => 'Сохранить',
    '_ch_sctr_btn_add' => 'Добавить',
    '_ch_sctr_btn_preview' => 'Предварительный просмотр',
    '_ch_sctr_btn_reset' => 'Сбросить',
    '_ch_sctr_btn_reset_all' => 'По умолчанию',
    '_ch_sctr_btn_publish' => 'Публикация',
    '_ch_sctr_btn_close' => 'Закрыть',
    '_ch_sctr_btn_delete' => 'Удалить',
    '_ch_sctr_btn_export' => 'Экспорт',
    '_ch_sctr_btn_import' => 'Импорт',

    '_ch_sctr_color' => 'Цвет',
    '_ch_sctr_use_image' => 'Использовать изображение',
    '_ch_sctr_image' => 'Изображение',
    '_ch_sctr_repeat' => 'Повторить',
    '_ch_sctr_position' => 'Позиция',
    '_ch_sctr_size' => 'Размер',
    '_ch_sctr_name' => 'Название',
    '_ch_sctr_style' => 'Стиль',
    '_ch_sctr_no' => 'Нет',
    '_ch_sctr_repeat_x' => 'Повторить по X',
    '_ch_sctr_repeat_y' => 'Повторить по Y',
    '_ch_sctr_none' => 'Ничего',
    '_ch_sctr_top_left' => 'По верхнему и левому краю',
    '_ch_sctr_top_center' => 'По верхнему краю и центру',
    '_ch_sctr_top_right' => 'По верхнему и правому краю',
    '_ch_sctr_center_left' => 'По центру и левому краю',
    '_ch_sctr_center' => 'По центру',
    '_ch_sctr_center_right' => 'По центру и правому краю',
    '_ch_sctr_bottom_left' => 'По нижнему и левому краю',
    '_ch_sctr_bottom_center' => 'По нижнему краю и центру',
    '_ch_sctr_bottom_right' => 'По нижнему и правому краю',
    '_ch_sctr_default' => 'По умолчанию',
    '_ch_sctr_normal' => 'Обычный',
    '_ch_sctr_bold' => 'Жирный',
    '_ch_sctr_italic' => 'Наклонный',
    '_ch_sctr_dotted' => 'Пунктирное',
    '_ch_sctr_dashed' => 'Штриховое',
    '_ch_sctr_solid' => 'Подчеркивание',
    '_ch_sctr_double' => 'Двойное',
    '_ch_sctr_groove' => 'Groove',
    '_ch_sctr_ridge' => 'Волнистое',
    '_ch_sctr_inset' => 'Вдавлено',
    '_ch_sctr_outset' => 'Выступ',
    '_ch_sctr_select_target' => 'Выбрать',
    '_ch_sctr_border_full' => 'Полный',
    '_ch_sctr_border_top' => 'Сверху',
    '_ch_sctr_border_right' => 'Справа',
    '_ch_sctr_border_bottom' => 'Снизу',
    '_ch_sctr_border_left' => 'Слева',
    '_ch_sctr_border_left_right' => 'Справа и сверху',
    '_ch_sctr_border_top_bottom' => 'Сверху и снизу',
    '_ch_sctr_border_top_right' => 'Сверху и справа',
    '_ch_sctr_border_right_bottom' => 'Справа и снизу',
    '_ch_sctr_border_bottom_left' => 'Снизу и слева',
    '_ch_sctr_border_left_top' => 'Слева и сверху',
    '_ch_sctr_caption' => 'Заголовок',
    '_ch_sctr_css_name' => 'Имя CSS',
    '_ch_sctr_type' => 'Тип',

    '_ch_sctr_publish' => 'Публикация новой темы',
    '_ch_sctr_name_theme' => 'Название',
    '_ch_sctr_thumbnail' => 'Миниатюра (64x64)',
    '_ch_sctr_err_add_theme' => 'Ошибка при создании новой темы.',
    '_ch_sctr_err_already_exist' => 'Тема с названием "%s" уже существует',
    '_ch_sctr_complete' => 'Новая тема создана успешно!',
    '_ch_sctr_import_complete' => 'Новая тема импортированы успешно!',
    '_ch_sctr_delete_complete' => 'Тема успешно удалена',
    '_ch_sctr_edit' => 'Редактировать',
    '_ch_sctr_form_edit' => 'Изменить запись',
    '_ch_sctr_form_add' => 'Добавить запись',
    '_ch_sctr_units' => 'Записи',
    '_ch_sctr_other_image' => 'Другое изображение',
    '_ch_sctr_err_conf_php' => 'Файл "%s" не найден',
    '_ch_sctr_err_theme_parameters' => 'Ошибка в параметрах темы',
    '_ch_sctr_err_delete_theme' => 'Ошибка удаления темы',
    '_ch_sctr_err_format' => 'Неверный формат файла',

    '_ch_sctr_administration' => 'Дизайн Сайта',
    '_ch_sctr_form_field_err' => 'Неверное значение',

    '_ch_sctr_js_reset' => 'Сбросить?',
    '_ch_sctr_js_err_theme_name' => 'Пожалуйста, заполните название темы',
    '_ch_sctr_js_err_choose_theme' => 'Выберите любую тему',
    '_ch_sctr_js_delete_theme' => 'Удалить тему?',
    '_ch_sctr_js_reset_page' => 'Сбросить страницу?',
);
