<?php

/**
 * This work, "Cheetah - https://www.cheetahwsb.com", is a derivative of "Dolphin Pro V7.4.2" by BoonEx Pty Limited - https://www.boonex.com/, used under CC-BY. "Cheetah" is licensed under CC-BY by Dean J. Bassett Jr.
 * CC-BY License - http://creativecommons.org/licenses/by/3.0/
 */

$aLangContent = array(
  '_sys_module_sites' => 'Sites',
  '_sys_module_ch_sites' => 'Sites',
  '_ch_site_caption_edit' => 'Edit Site',
  '_ch_sites' => 'Sites',
  '_ch_sites_action_add_site' => 'Add Site',
  '_ch_sites_action_add_to_featured' => 'Feature',
  '_ch_sites_action_my_sites' => 'My Sites',
  '_ch_sites_action_remove_from_featured' => 'Unfeature',
  '_ch_sites_action_title_delete' => 'Delete',
  '_ch_sites_action_title_edit' => 'Edit',
  '_ch_sites_adm_stats' => 'Pending Sites',
  '_ch_sites_admin' => 'Admin',
  '_ch_sites_admin_activate' => 'Activate',
  '_ch_sites_admin_clear_cache' => 'If you changed parameters below, <a href="javascript:void(0)" onclick="javascript:clearThumbCache();">Clear Screenshots Cache</a> to regenerate new ones.',
  '_ch_sites_admin_delete' => 'Delete',
  '_ch_sites_admin_refresh_thumb' => 'Refresh Thumbnail',
  '_ch_sites_admin_settings_info' => 'You can get "Access Key" and "Secret Key" by signing up for automated screenshots at: <a target="_blank" href="http://www.shrinktheweb.com/">ShrinkTheWeb</a>',
  '_ch_sites_admin_stw_note' => '<b>IMPORTANT NOTE:</b> By default, you must <a href="http://www.shrinktheweb.com/content/how-do-i-lock-my-account.html" target="_blank">add your server\'s IP address to ShrinkTheWeb\'s "Allowed Referrers" list</a>.',
  '_ch_sites_admin_top_menu_sitem' => 'Admin Sites',
  '_ch_sites_administration' => 'Sites',
  '_ch_sites_administration_add_site' => 'Add Site',
  '_ch_sites_administration_admin_sites' => 'Admin Sites',
  '_ch_sites_administration_settings' => 'Settings',
  '_ch_sites_administration_stw_acc_failed' => 'Failure on retrieving Account Info',
  '_ch_sites_administration_stw_acc_no_data' => 'Please enter your ShrinkTheWeb account details',
  '_ch_sites_administration_stw_acc_success' => 'Successfully retrieved Account Info',
  '_ch_sites_all_top_menu_sitem' => 'All Sites',
  '_ch_sites_bcaption_actions' => 'Actions',
  '_ch_sites_bcaption_administration' => 'Administration',
  '_ch_sites_bcaption_all' => 'All',
  '_ch_sites_bcaption_comments' => 'Comments',
  '_ch_sites_bcaption_description' => 'Description',
  '_ch_sites_bcaption_image' => 'Image',
  '_ch_sites_bcaption_information' => 'Information',
  '_ch_sites_bcaption_latest' => 'Recently Added Sites',
  '_ch_sites_bcaption_owner_sites' => 'My Sites',
  '_ch_sites_bcaption_previously' => 'Previously Rated',
  '_ch_sites_bcaption_rate' => 'Rate Site',
  '_ch_sites_bcaption_site_add' => 'Add Site',
  '_ch_sites_block_submenu_add_site' => 'Add',
  '_ch_sites_block_submenu_main' => 'Main',
  '_ch_sites_block_submenu_manage_sites' => 'Manage',
  '_ch_sites_block_submenu_pending_sites' => 'Pending Approval',
  '_ch_sites_calendar_top_menu_sitem' => 'Calendar',
  '_ch_sites_caption_allow_comments' => 'Allow to view and post comments',
  '_ch_sites_caption_allow_rate' => 'Allow rating',
  '_ch_sites_caption_allow_view' => 'View Site',
  '_ch_sites_caption_browse_add' => 'Add site',
  '_ch_sites_caption_browse_admin' => 'Admin Sites',
  '_ch_sites_caption_browse_all' => 'All Sites',
  '_ch_sites_caption_browse_by_category' => 'Browse Sites By Category: ',
  '_ch_sites_caption_browse_by_day' => 'Browse Sites By Day: ',
  '_ch_sites_caption_browse_by_tag' => 'Browse Sites By Tag: ',
  '_ch_sites_caption_browse_by_user' => 'Browse Sites By User: ',
  '_ch_sites_caption_browse_calendar' => 'Calendar Sites',
  '_ch_sites_caption_browse_categories' => 'Categories Sites',
  '_ch_sites_caption_browse_featured' => 'Featured Sites',
  '_ch_sites_caption_browse_manage' => 'Manage sites',
  '_ch_sites_caption_browse_my' => 'My Sites',
  '_ch_sites_caption_browse_pending' => 'Sites pending approval',
  '_ch_sites_caption_browse_popular' => 'Popular Sites',
  '_ch_sites_caption_browse_profile' => 'User Sites',
  '_ch_sites_caption_browse_search' => 'Search Sites',
  '_ch_sites_caption_browse_tags' => 'Tags Sites',
  '_ch_sites_caption_browse_top_rated' => 'Top Rated Sites',
  '_ch_sites_caption_categories' => 'Categories',
  '_ch_sites_caption_home' => 'Sites Home',
  '_ch_sites_caption_keyword' => 'Keyword',
  '_ch_sites_caption_public_feature' => 'Featured Sites',
  '_ch_sites_caption_public_last_featured' => 'Latest Featured Site',
  '_ch_sites_caption_public_latest' => 'Recently Added Public Sites',
  '_ch_sites_caption_search_results' => 'Search Results:',
  '_ch_sites_caption_share_site' => 'Share',
  '_ch_sites_caption_tags' => 'Tags',
  '_ch_sites_categories_top_menu_sitem' => 'Categories',
  '_ch_sites_err_edit_site' => 'Error updating the site',
  '_ch_sites_err_keyword' => 'Please specify a keyword in 3 to 100 characters',
  '_ch_sites_error_occured' => 'Error Occurred',
  '_ch_sites_featured_top_menu_sitem' => 'Featured',
  '_ch_sites_form_description' => 'Description',
  '_ch_sites_form_field_err' => 'incorrect value',
  '_ch_sites_form_other_thumbnail' => 'Other thumbnail',
  '_ch_sites_form_photo' => 'Photo',
  '_ch_sites_form_photo_inf' => 'Leave this field empty to allow the system to get an image automatically from provided URL.',
  '_ch_sites_form_title' => 'Title',
  '_ch_sites_form_url' => 'Url',
  '_ch_sites_home_top_menu_sitem' => 'Sites Home',
  '_ch_sites_hon' => 'Rater',
  '_ch_sites_hon_top_menu_sitem' => 'Rater',
  '_ch_sites_menu_my_sites_profile' => 'Sites',
  '_ch_sites_msg_access_denied' => 'Access Denied',
  '_ch_sites_msg_add_more_sites' => '<a href="%s">Click Here</a> to add more.',
  '_ch_sites_msg_added_to_featured' => 'Site was added to featured',
  '_ch_sites_msg_no_sites' => 'There are no sites yet.',
  '_ch_sites_msg_page_not_found' => 'Page Not Found',
  '_ch_sites_msg_pending_approval' => 'This site is pending administrator approval. Please wait.',
  '_ch_sites_msg_removed_from_featured' => 'Site was removed from featured',
  '_ch_sites_msg_you_have_active_sites' => '<a href="%s">%d Active Site(s)</a>',
  '_ch_sites_msg_you_have_pending_sites' => '<a href="%s">%d Pending Approval Site(s)</a>',
  '_ch_sites_msg_you_have_sites' => 'You have %s%s.',
  '_ch_sites_pending_approval' => 'Pending Approval',
  '_ch_sites_plural' => 'sites',
  '_ch_sites_poll_add' => '<a href="{profile_link}">{profile_nick}</a> added a new site <a href="{site_url}">{site_caption}</a>',
  '_ch_sites_poll_change' => '<a href="{profile_link}">{profile_nick}</a> changed site <a href="{site_url}">{site_caption}</a>',
  '_ch_sites_poll_commentPost' => '<a href="{profile_link}">{profile_nick}</a> commented on site <a href="{site_url}">{site_caption}</a>',
  '_ch_sites_poll_rate' => '<a href="{profile_link}">{profile_nick}</a> rated site <a href="{site_url}">{site_caption}</a>',
  '_ch_sites_popular_top_menu_sitem' => 'Popular',
  '_ch_sites_privacy_comment' => 'Comments',
  '_ch_sites_privacy_view' => 'View',
  '_ch_sites_privacy_vote' => 'Rate',
  '_ch_sites_profile_top_menu_sitem' => 'User Sites',
  '_ch_sites_sbs_comment' => 'New Site Comments',
  '_ch_sites_search_top_menu_sitem' => 'Search',
  '_ch_sites_single' => 'site',
  '_ch_sites_site' => 'Site',
  '_ch_sites_site_link_error' => 'This link does not appear to be working. Please check the URL and try again.',
  '_ch_sites_site_was_deleted' => 'Site was deleted',
  '_ch_sites_tags_top_menu_sitem' => 'Tags',
  '_ch_sites_top_menu_item' => 'Sites',
  '_ch_sites_top_top_menu_sitem' => 'Top Rated',
  '_ch_sites_unit_comments' => 'comments',
  '_ch_sites_unit_from' => 'From',
  '_ch_sites_wall_added_new' => 'added new',
  '_ch_sites_wall_added_new_title' => '{0} added new {1}',
  '_ch_sites_wall_added_new_items' => 'added {0} new sites',
  '_ch_sites_wall_added_new_title_items' => '{0} added {1} new sites',
  '_ch_sites_wall_added_new_comment' => 'commented on a',
  '_ch_sites_wall_added_new_title_comment' => '{0} commented on a {1}',
  '_ch_sites_wall_object' => 'site',
  '_mma_sites_add' => 'sites add',
  '_mma_sites_approve' => 'sites approve',
  '_mma_sites_browse' => 'sites browse',
  '_mma_sites_delete_any_site' => 'sites delete any site',
  '_mma_sites_edit_any_site' => 'sites edit any site',
  '_mma_sites_mark_as_featured' => 'sites mark as featured',
  '_mma_sites_search' => 'sites search',
  '_mma_sites_view' => 'sites view',
  '_wall_reposted_ch_sites_add' => 'reposted a site',
  '_wall_reposted_title_ch_sites_add' => '{0} reposted a site',
  '_wall_reposted_ch_sites_comment_add' => 'reposted a site comment',
  '_wall_reposted_title_ch_sites_comment_add' => '{0} reposted a site comment',
  '_sbs_txt_title_ch_sites' => 'Sites',
);
