<?php

/**
 * This work, "Cheetah - https://www.cheetahwsb.com", is a derivative of "Dolphin Pro V7.4.2" by BoonEx Pty Limited - https://www.boonex.com/, used under CC-BY. "Cheetah" is licensed under CC-BY by Dean J. Bassett Jr.
 * CC-BY License - http://creativecommons.org/licenses/by/3.0/
 */

$aLangContent = array(
    '_sys_module_profile_customize' => 'Profile Customizer',
    '_ch_profile_customize' => 'Profile Customizer',
    '_ch_profile_customize_page_themes' => 'Themes',
    '_ch_profile_customize_page_background' => 'Background',
    '_ch_profile_customize_page_font' => 'Fonts',
    '_ch_profile_customize_page_border' => 'Borders',
    '_ch_profile_customize_page_themes_my' => 'My themes',
    '_ch_profile_customize_page_themes_shared' => 'Shared themes',
    '_ch_profile_customize_page_import' => 'Import',
    '_ch_profile_customize_theme' => 'Theme',
    '_ch_profile_customize_btn_save' => 'Save',
    '_ch_profile_customize_btn_add' => 'Add',
    '_ch_profile_customize_btn_preview' => 'Preview',
    '_ch_profile_customize_btn_reset' => 'Reset',
    '_ch_profile_customize_btn_reset_all' => 'Reset page',
    '_ch_profile_customize_btn_publish' => 'Publish',
    '_ch_profile_customize_btn_close' => 'Close',
    '_ch_profile_customize_btn_delete' => 'Delete',
    '_ch_profile_customize_btn_export' => 'Export',
    '_ch_profile_customize_btn_import' => 'Import',

    '_ch_profile_customize_color' => 'Color',
    '_ch_profile_customize_use_image' => 'Use image',
    '_ch_profile_customize_image' => 'Image',
    '_ch_profile_customize_repeat' => 'Repeat',
    '_ch_profile_customize_position' => 'Position',
    '_ch_profile_customize_size' => 'Size',
    '_ch_profile_customize_name' => 'Name',
    '_ch_profile_customize_style' => 'Style',
    '_ch_profile_customize_no' => 'No',
    '_ch_profile_customize_repeat_x' => 'Repeat X',
    '_ch_profile_customize_repeat_y' => 'Repeat Y',
    '_ch_profile_customize_none' => 'None',
    '_ch_profile_customize_top_left' => 'Top Left',
    '_ch_profile_customize_top_center' => 'Top Center',
    '_ch_profile_customize_top_right' => 'Top Right',
    '_ch_profile_customize_center_left' => 'Center Left',
    '_ch_profile_customize_center' => 'Center',
    '_ch_profile_customize_center_right' => 'Center Right',
    '_ch_profile_customize_bottom_left' => 'Bottom Left',
    '_ch_profile_customize_bottom_center' => 'Bottom Center',
    '_ch_profile_customize_bottom_right' => 'Bottom Right',
    '_ch_profile_customize_default' => 'Default',
    '_ch_profile_customize_normal' => 'Normal',
    '_ch_profile_customize_bold' => 'Bold',
    '_ch_profile_customize_italic' => 'Italic',
    '_ch_profile_customize_dotted' => 'Dotted',
    '_ch_profile_customize_dashed' => 'Dashed',
    '_ch_profile_customize_solid' => 'Solid',
    '_ch_profile_customize_double' => 'Double',
    '_ch_profile_customize_groove' => 'Groove',
    '_ch_profile_customize_ridge' => 'Ridge',
    '_ch_profile_customize_inset' => 'Inset',
    '_ch_profile_customize_outset' => 'Outset',
    '_ch_profile_customize_select_target' => 'Select',
    '_ch_profile_customize_border_full' => 'Full',
    '_ch_profile_customize_border_top' => 'Top',
    '_ch_profile_customize_border_right' => 'Right',
    '_ch_profile_customize_border_bottom' => 'Bottom',
    '_ch_profile_customize_border_left' => 'Left',
    '_ch_profile_customize_border_left_right' => 'Left right',
    '_ch_profile_customize_border_top_bottom' => 'Top bottom',
    '_ch_profile_customize_border_top_right' => 'Top right',
    '_ch_profile_customize_border_right_bottom' => 'Right bottom',
    '_ch_profile_customize_border_bottom_left' => 'Bottom left',
    '_ch_profile_customize_border_left_top' => 'Left top',
    '_ch_profile_customize_caption' => 'Caption',
    '_ch_profile_customize_css_name' => 'Name of css',
    '_ch_profile_customize_type' => 'Type',

    '_ch_profile_customize_publish' => 'Publish new theme',
    '_ch_profile_customize_name_theme' => 'Name',
    '_ch_profile_customize_thumbnail' => 'Thumbnail(64x64)',
	'_ch_profile_customize_destination' => 'Destination',
    '_ch_profile_customize_err_add_theme' => 'Error creating new theme.',
    '_ch_profile_customize_err_already_exist' => 'A theme with name "%s" already exists',
    '_ch_profile_customize_complete' => 'New theme created successfully!',
    '_ch_profile_customize_import_complete' => 'New theme imported successfully!',
    '_ch_profile_customize_delete_complete' => 'Theme successfully deleted',
    '_ch_profile_customize_edit' => 'Edit',
    '_ch_profile_customize_form_edit' => 'Edit Entry',
    '_ch_profile_customize_form_add' => 'Add Entry',
    '_ch_profile_customize_units' => 'Entries',
    '_ch_profile_customize_other_image' => 'Other image',
    '_ch_profile_customize_err_conf_php' => 'File "%s" not found',
    '_ch_profile_customize_err_theme_parameters' => 'Error theme parameters',
    '_ch_profile_customize_err_delete_theme' => 'Error delete theme',
    '_ch_profile_customize_err_format' => 'Invalid file format',

    '_ch_profile_customize_administration' => 'Profile Customizer',
    '_ch_profile_customize_form_field_err' => 'Incorrect value',

    '_ch_profile_customize_js_reset' => 'Reset?',
    '_ch_profile_customize_js_err_theme_name' => 'Please fill in name of theme',
    '_ch_profile_customize_js_err_choose_theme' => 'Choose any theme',
    '_ch_profile_customize_js_delete_theme' => 'Delete theme?',
    '_ch_profile_customize_js_reset_page' => 'Reset page?',
);
