<?php

/**
 * This work, "Cheetah - https://www.cheetahwsb.com", is a derivative of "Dolphin Pro V7.4.2" by BoonEx Pty Limited - https://www.boonex.com/, used under CC-BY. "Cheetah" is licensed under CC-BY by Dean J. Bassett Jr.
 * CC-BY License - http://creativecommons.org/licenses/by/3.0/
 */

$sLangCategory = 'Cheetah Blogs';

$aLangContent = array(
    '_sys_module_blogs' => 'Blogs',
    '_ch_blog_added_spy' => '<a href="{profile_link}">{profile_nick}</a> added a new Post <a href="{post_url}">{post_caption}</a>',
    '_ch_blog_rated_spy' => '<a href="{profile_link}">{profile_nick}</a> rated a Post <a href="{post_url}">{post_caption}</a>',
    '_ch_blog_commented_spy' => '<a href="{profile_link}">{profile_nick}</a> commented a Post <a href="{post_url}">{post_caption}</a>',
    '_ch_blog_Categories' => 'Categories',
    '_ch_blog_Posts' => 'Posts',
    '_ch_blog_post' => 'Blog Post',
    '_ch_blog_post_view' => 'Post view',
    '_ch_blog_post_info' => 'Post info',
    '_ch_blog_All_Posts' => 'All Posts',
    '_ch_blog_Popular_Posts' => 'Popular Posts',
    '_ch_blog_Featured_Posts' => 'Featured Posts',
    '_ch_blog_Calendar' => 'Blog Posts Calendar',
    '_ch_blog_Blogs_Home' => 'Blogs Home',
    '_ch_blog_msg_access_denied' => 'Access Denied',
    '_ch_blog_pending_approval' => 'Pending Approval',
    '_ch_blog_blog_posts' => 'blog posts',
    '_ch_blog_stat_adm_stats' => 'pending blog posts',
    '_ch_blog_Latest_posts' => 'Latest posts',
    '_ch_blog_Top_blog' => 'Top blogs',
    '_ch_blog_Back_to_Blog' => 'Back to Blog',
    '_ch_blog_single' => 'blog posts',
    '_ch_blog_plural' => 'blog posts',
    '_ch_blog_caption_browse_by_day' => 'Browse Blog posts By Day: ',
    '_ch_blog_Comments_is_disabled' => 'Comments are disabled',
    '_ch_blog_privacy_comment' => 'Allow posting comments to',
    '_ch_blog_privacy_rate' => 'Allow rating to',
    '_ch_blog_privacy_view' => 'Allow viewing to',
    '_ch_blog_Administration' => 'Administration',
    '_ch_blog_Manage' => 'Manage',
	'_ch_blog_Manage_main' => 'Main',
    '_ch_blog_admin_box_desc' => 'You have {0} <a href="{1}">blog posts</a>. <a href="{2}">Click here</a> to add one.',
    '_ch_blog_My_blog' => 'My blog',
    '_ch_blog_Members_blog' => '{0}\'s blog',
    '_ch_blog_No_blogs_available' => 'No blogs available',
    '_ch_blog_All_Blogs' => 'All Blogs',
    '_ch_blog_Top_Blogs' => 'Top Blogs',
    '_ch_blog_Please_create_blog' => 'Please enter a Name for your blog before you start posting. You will only have to do this once.',
    '_ch_blog_description' => 'Briefly describe your blog (ie. \'My daily musings\' or  \'Funny stuff from Bubba\')',
    '_ch_blog_create_blog_form_error' => 'Blog description must be from 3 to 255 characters',
    '_ch_blog_Post_succ_updated' => 'Blog Post successfully updated',
    '_ch_blog_Post_fail_updated' => 'Failed to update Blog Post',
    '_ch_blog_Blogs' => 'Blogs',
    '_ch_blog_Blog' => 'Blog',
    '_ch_blog_My_posts' => 'My posts',
    '_ch_blog_RSS' => 'RSS',
    '_ch_blog_Edit_blog' => 'Edit blog',
    '_ch_blog_Delete_blog' => 'Delete blog',
    '_ch_blog_Edit_post' => 'Edit post',
    '_ch_blog_Caption_error' => 'please specify post title (from 3 to 255 characters)',
    '_ch_blog_Text_error' => 'please specify post text (from 3 to 65535 characters)',
    '_ch_blog_sbs_comments' => 'New Blog Comments',
    '_ch_blog_Top_Posts' => 'Top Posts',
    '_ch_blog_Add' => 'Add',
    '_ch_blog_wall_added_new' => 'added new',
	'_ch_blog_wall_added_new_title' => '{0} added new {1}',
    '_ch_blog_wall_added_new_items' => 'added {0} new blog posts',
	'_ch_blog_wall_added_new_title_items' => '{0} added {1} new blog posts',
    '_ch_blog_wall_added_new_comment' => 'commented on a',
	'_ch_blog_wall_added_new_title_comment' => '{0} commented on a {1}',
    '_ch_blog_wall_object' => 'blog post',
    '_ch_blog_chart' => 'Blog Posts',
    '_ch_blog_stat' => 'Blog Posts',
	'_wall_reposted_ch_blogs_create' => 'reposted a blog post',
	'_wall_reposted_title_ch_blogs_create' => '{0} reposted a blog post',
	'_wall_reposted_ch_blogs_comment_add' => 'reposted a blog post comment',
	'_wall_reposted_title_ch_blogs_comment_add' => '{0} reposted a blog post comment',
    '_sbs_txt_title_ch_blogs' => 'Blogs',
    '_mma_blog_view' => 'blog view',
    '_mma_blog_post_view' => 'blog post view',
    '_mma_blogs_browse' => 'blogs browse',
    '_mma_blogs_posts_browse' => 'blogs posts browse',
    '_mma_blog_post_search' => 'blog post search',
    '_mma_blog_post_add' => 'blog post add',
    '_mma_blog_posts_edit_any_post' => 'blog posts edit any post',
    '_mma_blog_posts_delete_any_post' => 'blog posts delete any post',
    '_mma_blog_posts_approving' => 'blog posts approving',
    '_mma_blog_posts_comments_delete_and_edit' => 'blog delete and edit comments',
);
