<?php

/**
 * This work, "Cheetah - https://www.cheetahwsb.com", is a derivative of "Dolphin Pro V7.4.2" by BoonEx Pty Limited - https://www.boonex.com/, used under CC-BY. "Cheetah" is licensed under CC-BY by Dean J. Bassett Jr.
 * CC-BY License - http://creativecommons.org/licenses/by/3.0/
 */

$aLangContent = array(
  '_sys_module_poll' => 'Опрос',
  '_ch_poll' => 'Опрос',
  '_ch_poll_PH' => 'Пользовательские опросы',
  '_ch_poll_access_denied' => 'Доступ запрещен',
  '_ch_poll_actions' => 'Действия',
  '_ch_poll_active' => 'Активный опрос',
  '_ch_poll_add' => 'Добавить опрос',
  '_ch_poll_added' => '<a href="{profile_link}">{profile_nick}</a> добавил новый опрос <a href="{poll_url}">{poll_caption}</a>',
  '_ch_poll_administration' => 'Администрирование',
  '_ch_poll_all' => 'Недавние',
  '_ch_poll_allow_comment' => 'Комментарии доступны',
  '_ch_poll_allow_view' => 'Просмотр доступен',
  '_ch_poll_allow_vote' => 'Голосование доступно',
  '_ch_poll_answer' => 'Ответ',
  '_ch_poll_answer_length_required' => 'ответы должны быть от {0} до {1} символов длиной, и Вы должны ответить более, чем на один вопрос',
  '_ch_poll_answered' => '<a href="{recipient_p_link}">{recipient_p_nick}</a> <a href="{poll_link}">отпрос</a> был отвечен <a href="{profile_link}">{profile_nick}</a>',
  '_ch_poll_approve' => 'Одобрить',
  '_ch_poll_approved' => 'Одобренные',
  '_ch_poll_browse_by_day' => 'Просмотр опросов по дню',
  '_ch_poll_browse_category' => 'Просмотр опросов по категории',
  '_ch_poll_browse_tag' => 'Просмотр опросов по тегу',
  '_ch_poll_by' => 'От',
  '_ch_poll_calendar' => 'Календарь',
  '_ch_poll_categories' => 'Категории',
  '_ch_poll_close' => 'Закрыть',
  '_ch_poll_commented' => '<a href="{recipient_p_link}">{recipient_p_nick}</a> <a href="{poll_link}">опрос</a> был прокомментирован <a href="{profile_link}">{profile_nick}</a>',
  '_ch_poll_comments' => 'Комментарии',
  '_ch_poll_create' => 'Создать опрос',
  '_ch_poll_created' => 'Опрос был создан',
  '_ch_poll_delete' => 'Удалить',
  '_ch_poll_disapprove' => 'Отклонить',
  '_ch_poll_edit' => 'Изменить',
  '_ch_poll_edit_poll' => 'Изменить опрос',
  '_ch_poll_featured' => 'В избранное',
  '_ch_poll_featured_polls' => 'Избранные',
  '_ch_poll_generate' => 'Создать',
  '_ch_poll_have_not_approval' => 'У Вас {0} отклоненных опросов',
  '_ch_poll_home' => 'Главная',
  '_ch_poll_item_not_found' => 'Опрос не найден',
  '_ch_poll_keyword' => 'опрос, мнение, диаграмма',
  '_ch_poll_latest' => 'Последние опросы',
  '_ch_poll_latest_public' => 'Последние публичные опросы',
  '_ch_poll_loading' => 'загрузка',
  '_ch_poll_main' => 'Главная',
  '_ch_poll_make_it' => 'сделать',
  '_ch_poll_manage' => 'Управление',
  '_ch_poll_manage_poll' => 'Управление опросом',
  '_ch_poll_max_reached' => 'Достигнуто максимальное количество опросов',
  '_ch_poll_moderation' => 'Опросы пост-модерация',
  '_ch_poll_module' => 'Опросы',
  '_ch_poll_my' => 'Мои опросы',
  '_ch_poll_not_available' => 'Опрос недоступен',
  '_ch_poll_owner' => 'Информация',
  '_ch_poll_pending' => 'На модерации',
  '_ch_poll_pending_poll' => 'Смотреть ожидающие',
  '_ch_poll_popular' => 'Популярные',
  '_ch_poll_popular_polls' => 'Популярные опросы',
  '_ch_poll_privacy_comment_error' => 'Настройки конфиденциальности получателя не позволяют Вам оставлять комментарии',
  '_ch_poll_privacy_vote_error' => 'Настройки конфиденциальности получателя не позволяют Вам голосовать',
  '_ch_poll_private' => 'Приватный опрос',
  '_ch_poll_question' => 'Вопрос',
  '_ch_poll_question_length_required' => 'длина вопроса должна быть от {0} до {1} символов',
  '_ch_poll_rated' => '<a href="{recipient_p_link}">{recipient_p_nick}</a> <a href="{poll_link}">опрос</a> был оценен <a href="{profile_link}">{profile_nick}</a>',
  '_ch_poll_result' => 'Результат',
  '_ch_poll_save' => 'Сохранить',
  '_ch_poll_sbs_comment' => 'Новые комментарии к опросу',
  '_ch_poll_search' => 'Поиск',
  '_ch_poll_select_all' => 'Выбрать все',
  '_ch_poll_settings' => 'Настройки',
  '_ch_poll_specify_least' => 'Вам нужно указать минимум одного пользователя',
  '_ch_poll_tags' => 'Теги',
  '_ch_poll_tags_premoderation' => 'Опросы',
  '_ch_poll_tags_separeted' => 'Укажите несколько слов, разделенных запятыми или точкой с запятой',
  '_ch_poll_unapproved' => 'Отклоненные',
  '_ch_poll_unfeatured' => 'Не избранное',
  '_ch_poll_view' => 'Опрос: {0}',
  '_ch_poll_view_category' => 'Смотреть по категории',
  '_ch_poll_view_tag' => 'Смотреть по тегу',
  '_ch_poll_votings' => 'Голоса',
  '_ch_poll_wall_added_new' => 'добавил новый',
  '_ch_poll_wall_added_new_title' => '{0} добавил новый {1}',
  '_ch_poll_wall_added_new_comment' => 'прокомментировал',
  '_ch_poll_wall_added_new_title_comment' => '{0} прокомментировал {1}',
  '_ch_poll_wall_object' => 'опрос',
  '_ch_poll_was_deleted' => 'Опрос был удачно удален',
  '_ch_poll_was_edited' => 'Опрос был удачно изменен',
  '_ch_polls' => 'Опросы',
  '_ch_polls_profile' => 'Опросы',  
  '_ch_polls_adm_stats' => 'Ожидающие опросы',
  '_ch_polls_profile' => 'Опросы профиля',
  '_ch_polls_public' => 'Публичные опросы',
  '_mma_create_polls' => 'Опросы: создавать',
  '_wall_reposted_ch_poll_add' => 'зарепостил опрос',
  '_wall_reposted_title_ch_poll_add' => '{0} зарепостил опрос',
  '_wall_reposted_ch_poll_comment_add' => 'зарепостил комментарий к опросу',
  '_wall_reposted_title_ch_poll_comment_add' => '{0} зарепостил комментарий к опросу',
  '_sbs_txt_title_ch_poll' => 'Опрос',
);
